const foodList = [
  {
    id: 1,
    title: "menudo",
    imageUrl: require("../assets/pork-menudo.png"),
    ingredients: [
      "2 lbs. pork",
      "1/4 lb. pig liver",
      "1 cup potatoes diced",
      "1 piece carrot cubed",
      "1/2 cup soy sauce",
      "1/2 piece lemon",
      "1 piece onion chopped",
      "3 cloves garlic minced",
      "1 teaspoon sugar",
      "3/4 cup tomato sauce",
      "4 pieces hotdogs sliced diagonally",
      "2 tablespoons cooking oil",
      "2 to 3 pieces dried bay leaves",
      "salt and pepper to taste",
    ],
    instructions: [
      "Combine pork, soysauce, and lemon in a bowl. Marinate for at least 1 hour.",
      "Heat oil in a pan",
      "Saute garlic and onion.",
      "Add the marinated pork. Cook for 5 to 7 minutes.",
      "Pour in tomato sauce and water and then add the bay leaves.Let boil and simmer for 30 minutes to an hour depending on the toughness of the pork. Note: Add water as necessary.",
      "Add-in the liver and hot dogs.Cook for 5 minutes.",
      "Put-in potatoes, carrots, sugar,salt, and pepper. Stir and cook for 8 to 12 minutes.",
      "Put-in potatoes, carrots, sugar,salt, and pepper. Stir and cook for 8 to 12 minutes.",
    ],
  },
  {
    id: 2,
    title: "caldereta",
    imageUrl: require("../assets/caldereta.png"),
    ingredients: [
      "2 lbs beef cubed",
      "3 pieces garlic cloves crushed and chopped",
      "1 piece onion finely chopped",
      "2 cups beef broth",
      "1 piece red bell pepper sliced",
      "1 piece green bell pepper sliced",
      "1 cup tomato sauce",
      "½ cup liver spread processed using blender",
      "1 teaspoon chili flakes",
      "3 pieces dried bay leaves",
      "2 cups potatoes sliced",
      "2 cups carrots sliced",
      "1/4 cup cooking oil",
      "⅔ cup green olives",
      "salt and pepper to taste",
    ],
    instructions: [
      "Heat the cooking oil in the cooking pot or pressure cooker.",
      "Sauté the onion and garlic.",
      "Add the beef. Cook for 5 minutes or until the color turns light brown.",
      "Add the dried bay leaves and chili flakes or crushed pepper. Stir.",
      "Add the liver spread. Stir.",
      "Pour-in the tomato sauce and beef broth.",
      "Cook the beef until it becomes tender (about 30 mins if using a pressure cooker, or 1 to 2 hours if using an ordinary pot).",
      "Add potato and carrots. Cook for 8 to 10 minutes.",
      "Put the green olives and bell peppers in the cooking pot. Stir and continue to cook for 5 minutes more.",
      "Add salt and pepper to taste.",
      "Serve Hot. Enjoy!",
    ],
  },
  {
    id: 3,
    title: "dinuguan",
    imageUrl: require("../assets/dinuguan.png"),
    ingredients: [
      "1 lb pork cut into cubes",
      "1 cup vinegar",
      "2 pieces long green pepper",
      "1 1/2 tablespoon brown sugar",
      "1 piece onion chopped finely",
      "1 tablespoon garlic minced",
      "3 tablespoon cooking oil",
      "1 cup water",
      "10 oz pork blood",
      "1 piece pork cube boullion",
      "salt and pepper to taste",
    ],
    instructions: [
      "Heat oil in a pan. Sauté garlic and onion.",
      "Once the onion softens, add pork. Continue to sauté for 5 minutes or until light brown.",
      "Pour water. Let boil.",
      "Add  pork cube. Cook in low heat until the meat tenderizes.",
      "Add pork blood. Stir. Cook for 8 to 10 minutes while stirring. ",
      "Pour vinegar and add sugar and long green pepper. Cook for 12 to 15 minutes.",
      "Season with salt and pepper as needed. Serve hot with puto.",
    ],
  },
];

export default foodList;
